// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGsGMU8n2ImJ8nSmoqtBwie4xEnt8A4sw',
    appId: '1:436314290163:android:9d38a80e45ffd948a34486',
    messagingSenderId: '436314290163',
    projectId: 'arosa-26dc8',
    storageBucket: 'arosa-26dc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWI1nTg8TBuOPmyB3pSgcJD_zS3wp_u-w',
    appId: '1:436314290163:ios:6ea5c5f60baad3afa34486',
    messagingSenderId: '436314290163',
    projectId: 'arosa-26dc8',
    storageBucket: 'arosa-26dc8.appspot.com',
    androidClientId: '436314290163-vfv3sat4ee64rhv6f2bfhi0uk780cfqv.apps.googleusercontent.com',
    iosClientId: '436314290163-or6hj6phicvug0iqi7kh9apahqpuvj3d.apps.googleusercontent.com',
    iosBundleId: 'ma.Eddouche.arosa',
  );
}
